### ISSUE TITLE
Problem with QT and webkit webkitwidgets

### ISSUE THREAD

**Issue by josuem** [bartoszek/AUR-openboard#1]
Hi. I can't install openboard on Archlinux. Using yay -S openboard I have:
```bash
==> Iniciando build()...
Info: creating stash file /home/josue/Downloads/AUR-openboard-master/src/OpenBoard-1.5.4/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets
```
I think it is because of the qt version. I have try to install openboard-git, openboard-develop and openboard-develop-git but I have the same problem.

**Comment by bartoszek** [comment]
[Everything builds fine here](https://travis-ci.org/github/bartoszek/AUR-openboard-git/builds), could you please post full build log
* Build in container with `extra-x86_64-build -r /tmp/openboard-build -- -- --log` to produce logs
  * `extra-x86_64-build` is provided by `devtools` package
* Rename the `openboard-...-build.log` to `openboard-...-build.log.txt` and drop it into GitHub comment box 🛠️ 
* You can remove build container after that `sudo rm -rf /tmp/openboard-build`)

**Comment by rustombhesania** [comment]
hey im facing the same problem of 
`==> Starting build()...
Info: creating stash file /home/rben10/.cache/yay/openboard-git/src/OpenBoard/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets
==> ERROR: A failure occurred in build().
    Aborting...
error making: openboard-git
` 
it Seems a problem with qt webkit so i installed `qt5-webkit` following the Aur thread but its the same error, Heres the full error 
`(base) [rben10@senpai ~]$ yay openboard
7 aur/openboardview-inflex 2018062301-1 (+0 0.00) (Out-of-date: 2020-01-12) 
    Linux SDL/ImGui edition software for viewing .brd files
6 aur/openboard-develop 1.6.0-4 (+0 0.00) 
    Interactive whiteboard software for schools and universities
5 aur/openboard-develop-git 1.6.0a3.r16.gab705d28-1 (+0 0.00) 
    Interactive whiteboard software for schools and universities
4 aur/openboard-git v1.5.4.r0.g85eb094e-1 (+2 0.01) 
    Interactive whiteboard software for schools and universities
3 aur/openboardview 8.0-1 (+3 0.00) 
    Linux SDL/ImGui edition software for viewing .brd files
2 aur/openboardview-git r646.befed74-1 (+11 0.14) 
    Linux SDL/ImGui edition software for viewing .brd files
1 aur/openboard 1.5.4-3 (+34 0.83) 
    Interactive whiteboard software for schools and universities
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 4
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  openboard-git-v1.5.4.r0.g85eb094e-1

  1 openboard-git                    (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): openboard-git
  1 openboard-git                    (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: openboard-git
==> Making package: openboard-git v1.5.4.r0.g85eb094e-1 (Saturday 03 April 2021 04:49:34 PM)
==> Retrieving sources...
  -> Updating OpenBoard git repo...
Fetching origin
  -> Found qchar.patch
  -> Found qwebkit.patch
  -> Found openboard.desktop
  -> Found quazip.patch
  -> Found poppler.patch
  -> Found drop_ThirdParty_repo.patch
  -> Found 30fps.patch
==> Validating source files with sha256sums...
    OpenBoard ... Skipped
    qchar.patch ... Passed
    qwebkit.patch ... Passed
    openboard.desktop ... Passed
    quazip.patch ... Passed
    poppler.patch ... Passed
    drop_ThirdParty_repo.patch ... Passed
    30fps.patch ... Passed
==> Making package: openboard-git v1.5.4.r0.g85eb094e-1 (Saturday 03 April 2021 04:49:36 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating OpenBoard git repo...
Fetching origin
  -> Found qchar.patch
  -> Found qwebkit.patch
  -> Found openboard.desktop
  -> Found quazip.patch
  -> Found poppler.patch
  -> Found drop_ThirdParty_repo.patch
  -> Found 30fps.patch
==> Validating source files with sha256sums...
    OpenBoard ... Skipped
    qchar.patch ... Passed
    qwebkit.patch ... Passed
    openboard.desktop ... Passed
    quazip.patch ... Passed
    poppler.patch ... Passed
    drop_ThirdParty_repo.patch ... Passed
    30fps.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of OpenBoard git repo...
Cloning into 'OpenBoard'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
patching file libs.pri
patching file OpenBoard.pro
patching file src/core/UBTextTools.cpp
patching file resources/forms/trapFlash.ui
patching file OpenBoard.pro
patching file plugins/cffadaptor/UBCFFAdaptor.pro
patching file libs.pri
patching file OpenBoard.pro
patching file src/pdf/XPDFRenderer.cpp
patching file src/pdf/XPDFRenderer.h
==> Starting pkgver()...
==> Sources are ready.
==> Making package: openboard-git v1.5.4.r0.g85eb094e-1 (Saturday 03 April 2021 04:49:40 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Info: creating stash file /home/rben10/.cache/yay/openboard-git/src/OpenBoard/.qmake.stash
Project ERROR: Unknown module(s) in QT: webkit webkitwidgets
==> ERROR: A failure occurred in build().
    Aborting...
error making: openboard-git`

**Comment by bartoszek** [comment]
Looks like a tainted local system, try rebuilding in clean chroot, please.
