### ISSUE TITLE
openboard: error while loading shared libraries: libpoppler.so.122

### ISSUE THREAD

**Issue by CryptLabs** [bartoszek/AUR-openboard#13]
Hello,

I am unable to launch the application.
This error occurs whenever I make an attempt to carry out the aforementioned action:

`openboard: error while loading shared libraries: libpoppler.so.122: cannot open shared object file: No such file or directory`

The libpoppler currently installed is  libpoppler.so.124

Regards

**Comment by bartoszek** [comment]
Common issue with `AUR` packages.
After dependency update e.q: libpoppler all related `AUR` packages needs a rebuild ¯\_(ツ)_/¯
You can use the `rebuild-detector` package to alleviate the issue, it will inform you during sys update about outdated packages.
