### ISSUE TITLE
Multithreaded compilation

### ISSUE THREAD

**Issue by LunarEclipse363** [bartoszek/AUR-openboard#15]
The current package takes forever to build on modern hardware (Ryzen 7 4800H), I suggest you apply the following patch so that make makes use of all the cores in your computer.

```patch
diff --git a/PKGBUILD b/PKGBUILD
index d78e2ca..a0a49d7 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -44,7 +44,7 @@ build() {
 # convert translations to binary form
   lrelease OpenBoard.pro
   qmake OpenBoard.pro -spec linux-g++
-  make
+  make -j $(nproc --ignore 1)
 }

 package() {
 ```
 
This will use N-1 threads, but at least 1 (where N is the number of threads your CPU provides). As to why not use all the threads, this helps to keep your computer usable while making the package.

**Comment by bartoszek** [comment]
Well, it's up to the user to define the number of concurrent jobs for the make server.

One can do it globally in `/etc/makepkg.conf`: changing the `MAKEFAGS` variable there.
Or in `makepkg` call by passing the `MAKEFLAGS` variable there e.g: `makepkg MAKEFLAGS="-j12"`
Most aur helpers allow to to pass extra makepkg switches: `--mflags` (yay,paru) `--margs` (aurutils)
```sh
paru install blender-git --mflags="MAKEFLAGS=\"-j $(nproc --ignore 1)\""
```
Force `PKGBUILD` to use multithreading by default would devote user of after mentioned flexibility ¯\\\_(ツ)\_/¯
