### ISSUE TITLE
Poppler version issue

### ISSUE THREAD

**Issue by RPG-Alex** [bartoszek/AUR-openboard#16]
Updated from AUR and now after install when trying to run I see this message:
`openboard: error while loading shared libraries: libpoppler.so.125: cannot open shared object file: No such file or directory`

System is showing these popplers:
`libpoppler.so          libpoppler.so.126      libpoppler.so.126.0.0`

So no 125... Not sure what the work around is.

**Comment by RPG-Alex** [comment]
> Updated from AUR and now after install when trying to run I see this message: `openboard: error while loading shared libraries: libpoppler.so.125: cannot open shared object file: No such file or directory`
> 
> System is showing these popplers: `libpoppler.so libpoppler.so.126 libpoppler.so.126.0.0`
> 
> So no 125... Not sure what the work around is

Alright so until whatever error causes this to throw is solved, uninstalling openboard, rebuidilng it from this repo and then reinstalling it fresh seems to have worked.

**Comment by bartoszek** [comment]
@RPG-Alex It's just the AUR idiosyncrasy ¯\\\_(ツ)\_/¯
Pacman assumes that the repository you're using is coherent and assumes that dependency versions are met, which is fine for Archs own repos, but for packages installed from AUR user is responsible for keeping them in sync with deps.
You can use the rebuild-detectro Pacman hook to notify you at each sys upgrade which packages require rebuild after dependency upgrade, but still, you'll have to perform the upgrade manually. As far as I can tell there's no AUR Helper that will do that for you.
https://github.com/maximbaz/rebuild-detector
