### ISSUE TITLE
bug plopper library version don't correpond

### ISSUE THREAD

**Issue by ArnaudDURAND** [bartoszek/AUR-openboard#17]
Hello, openboard don't start.
I think it's wrong version of poppler.

[arnaud@arnaud-linncplusp1 ~]$ openboard 
openboard: error while loading shared libraries:
libpoppler.so.124: cannot open shared object file: No such file or directory

The version of libpoppler.so is 125
/usr/lib/libpoppler.so
/usr/lib/libpoppler.so.125
/usr/lib/libpoppler.so.125.0.0

**Comment by bartoszek** [comment]
Rebuild your `openboard` package, also install `rebuild-detectro` to notify you on each system update witch AUR packages requires rebuild.
