### ISSUE TITLE
Openboard failing in latest Manjaro update

### ISSUE THREAD

**Issue by adelnoureddine** [bartoszek/AUR-openboard#2]
In the most recent Manjaro updates, yesterday, OpenBoard fails to start with :
`openboard: error while loading shared libraries: libpoppler.so.105: cannot open shared object file: No such file or directory`
There is a libpoppler.so.106 in /usr/bin, but with creating a symlink to it named libpoppler.so.105, I can start OpenBoard, but importing PDF fails with a segmentation fault error.

**Comment by bartoszek** [comment]
Please rebuild the package, you can use rebuild-detector to get notification of outdated packages each time you are doing system upgrade.

**Comment by adelnoureddine** [comment]
Thanks, indeed rebuilding the package solves the problem. I've also installed rebuild detector for future updates.
