### ISSUE TITLE
Flickering interface with version 1.6.1-2

### ISSUE THREAD

**Issue by iGormilhit** [bartoszek/AUR-openboard#4]
I've opened an issue on the Openboard projet (https://github.com/OpenBoard-org/OpenBoard/issues/526). On archlinux (and endeavourOS), with openboard on version 1.6.1.-2 installed through your package (and even with a flatpak installation), there's some interface flickering, especially when the user switch from the desktop view to the document view, and at the application start up. Sometimes, it's only a few times, but sometimes it doesn't end util the user tries to switch to another application.

I'm using Gnome on version 40. I tried with wayland or xorg, without any differences.

I'm curious if someone else encountered the same issue. I'm also wondering if it could be caused by the Qt version, as Openboard ensures compatibility with Qt 5.5 and on arch, Qt is 5.15.

**Comment by bartoszek** [comment]
I've dropped gnome since they dropped the last feature that kept me around, mainly vertical workspaces, those can't really help you with any gnome>=3.34 issues, sorry.
Did you tired `openboard-git` package - perhaps it could have the fix already upstream but it wasn't published in a tagged release?

**Comment by iGormilhit** [comment]
Thanks for your answer. I tried `openboard-git` and got the same behaviour.

**Comment by bartoszek** [comment]
Could you perhaps try record the screen and post it in the main issue thread? Shortcut is shift+alt+ctrl+R if I recall correctly.

**Comment by bartoszek** [comment]
[sic!] my English is soo broken here, I can barely understand what going on...
