### ISSUE TITLE
Fatal error at installation

### ISSUE THREAD

**Issue by faustXman** [bartoszek/AUR-openboard#5]
src/adaptors/UBExportDocument.cpp:46:14: fatal error: quazip.h: No such file or directory
   46 |     #include "quazip.h"
      |              ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.Release:3281: build/linux/release/objects/UBExportDocument.o] Error 1
make[1]: Leaving directory '/home/faustd/Downloads/OpenBoard-1.6.1'
make: *** [Makefile:42: release] Error 2

same error I get when either git clone or build from scratch

**Comment by iGormilhit** [comment]
Hello,

Same issue here. On my archlinux, the `quazip` version is `1.2-1`. I've tried to understand what's explained in the AUR comments, but it's not clear to me.

**Comment by bartoszek** [comment]
@iGormilhit Quick fix, just need to replace `1.1` with `1.2` following quazip update from `1.1` to `1.2`, btw. AUR comments are mostly unmoderated babbling 😏

**Comment by iGormilhit** [comment]
@bartoszek Thanks a lot! I think that `openboard-git` has the same issue. :slightly_smiling_face:

**Comment by wdfinch** [comment]
Hi, I'm getting this error when trying to install. I just started using arch the other day so I'm new. I thought that `yay` would install all the deps needed for the package. Do I need to install something else to get this working?

**Comment by bartoszek** [comment]
@wdfinch yep, `quazip=1.3` landed in main repo yesterday, will update shortly.
@fsiegert need a small favour here mate 🥲

**Comment by fsiegert** [comment]
Hi @bartoszek ,

Sure, which favour? Do you want me to make the change directly in AUR, or are you already working on it?

Best,  
Frank

**Comment by bartoszek** [comment]
@fsiegert bumping `quazip` version to 1.3 in the include path here should be enough:
https://github.com/bartoszek/AUR-openboard/blob/master/quazip.patch#L7-L42
I'll be back home next week and alleviate you form maintenance burden •́  ‿ ,•̀

**Comment by fsiegert** [comment]
Sorry about the slow response, I have finally managed to find the time to update my installation and fix the issues with OpenBoard compilation in AUR. At the same time I have updated to OpenBoard 1.6.2. Please give the latest version in AUR a try and let me know if there are still any issues.

This ticket can be closed.
