### ISSUE TITLE
Fails to build on Manjaro

### ISSUE THREAD

**Issue by dpearson1983** [bartoszek/AUR-openboard#6]
I installed this a while ago while exploring alternatives to Microsoft Whiteboard, and an update showed up yesterday. The update fails to build with the error:

```
src/adaptors/UBExportDocument.cpp:46:14: fatal error: quazip.h: No such file or directory
   46 |     #include "quazip.h"
      |              ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.Release:3287: build/linux/release/objects/UBExportDocument.o] Error 1
make[1]: Leaving directory '/var/cache/private/pamac/openboard/src/OpenBoard-1.6.1'
make: *** [Makefile:42: release] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Finished with result: exit-code
```

Seems like maybe a file wasn't added to the repo with the quazip patch stuff that seems to have been pushed yesterday?

I've saved all the text output during the build process to a text file, so let me know if you want to see more. I'm running the most up-to-date Manjaro on the 5.10 LTS kernel. Let me know if you need any more info and I will be glad to provide it.

**Comment by bartoszek** [comment]
Manjaro is lagging behind ¯\\\_(ツ)\_/¯ just postpone the update until `quazip:1.2` landed in the Manjaro repository.
I can't handle all aberrations resulting from Arch derivatives, sorry 😏 

btw. isn't Manjaro at `1.2` version of `quazip` already 🤔

**Comment by bartoszek** [comment]
@dpearson1983 Perhaps you can aid me here, what is the equivalent of `pacstrap` for manjaro? I've tried to use `manjaro-bootstrap.sh`  but it looks abandoned and doesn't work out of the box https://gitlab.manjaro.org/tools/maintenance-tools/manjaro-bootstrap

If I could spin up a Manjaro chroot in ~30s adding it to my CI integration would prevent such issues in the future.

**Comment by dpearson1983** [comment]
@bartoszek Sorry, I'm pretty new to Manjaro (switched over from Fedora, which I had used for about a decade, maybe 5 months ago). I did do some searching and found this: [](https://www.linuxquestions.org/questions/manjaro-119/manjaro-pacstrap-4175578519/)

I installed the arch-install-scripts package and now this package builds successfully. Of course, quazip is also version 1.2 now, and I don't know when that updated, so that could also be what fixed things. Either way, I think this issue can close now.

**Comment by bartoszek** [comment]
@dpearson1983 Thanks for clarifying, I'll try to inspect this further, as my only Manjaro installation is a laptop I rarely ever use, and still trying to figure out how to quickly create Manjaro container from Arch this could take a while...

**Comment by dpearson1983** [comment]
@bartoszek Seems like there is a docker image, but I don't know how up-to-date it might be: [https://hub.docker.com/r/jonathonf/manjaro/](https://hub.docker.com/r/jonathonf/manjaro/)

I also found this reddit thread that might be helpful: [https://www.reddit.com/r/Crostini/comments/etf0gz/has_anyone_gotten_a_manjaro_container_running/](https://www.reddit.com/r/Crostini/comments/etf0gz/has_anyone_gotten_a_manjaro_container_running/)

and this from the guy that built the docker image: [https://archived.forum.manjaro.org/t/how-to-build-your-own-manjaro-base-image-for-docker/29674](https://archived.forum.manjaro.org/t/how-to-build-your-own-manjaro-base-image-for-docker/29674)

Don't worry too much about this if it's too much additional work. For now, at least, I'm not going to be using Openboard as it's a bit too clunky in the way you have to use some tools (ruler, protractor, etc). My interest is, as usual, trying to get away from Microsoft. I was using Microsoft Whiteboard on my Surface Pro 6 connected to projectors to teach my classes. They pushed an "update" to Whiteboard that removed almost every useful feature but added the ability to react with emojis. They have since rolled back those changes after major user backlash, but I had already switched to OneNote in the meantime (unfortunately another Microsoft program). I would like to eventually get rid of Windows on my Surface and find a good alternative to Whiteboard/OneNote, but I don't have the downtime for that right now and probably won't for quite some time.
