### ISSUE TITLE
Fails to install on Manjaro [Workaround]

### ISSUE THREAD

**Issue by kampfsau** [bartoszek/AUR-openboard#7]
==> Starting prepare()...
  -> drop_ThirdParty_repo
The next patch would create the file libs.pri,
which already exists!  Assume -R? [n] y
patching file libs.pri
Hunk #1 FAILED at 1.
Not deleting file libs.pri as content differs from patch
1 out of 1 hunk FAILED -- saving rejects to file libs.pri.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
:: failed to verify integrity or prepare openboard package

Removing the libs.pri file in ~/.cache/pacaur/openboard/src/OpenBoard-1.6.1/ manually resolved it.

**Comment by bartoszek** [comment]
I've forced the patches to fix this, as reworking them would be too much of a hassle 😏
